//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _WX_HIYA_WXCRAFTER_BASE_CLASSES_H
#define _WX_HIYA_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/bmpbuttn.h>
#include <wx/statline.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainDialogBaseClass : public wxDialog
{
protected:
    wxBitmapButton* m_bmpButton17;
    wxStaticLine* m_staticLine15;
    wxButton* m_buttonOK;
    wxButton* m_buttonCancel;

protected:
    virtual void Hooke(wxCommandEvent& event)
    {
        event.Skip();
    }

public:
    wxBitmapButton* GetBmpButton17()
    {
        return m_bmpButton17;
    }
    wxStaticLine* GetStaticLine15()
    {
        return m_staticLine15;
    }
    wxButton* GetButtonOK()
    {
        return m_buttonOK;
    }
    wxButton* GetButtonCancel()
    {
        return m_buttonCancel;
    }
    MainDialogBaseClass(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("My Dialog"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(500, 300),
        long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
    virtual ~MainDialogBaseClass();
};

#endif
